# config file with pipeline defaults

PATHS:
    # ----- CUSTOM -----
    # (edit) list of fastq file full path names, sample identifiers and groupings
    INPUT_SAMPLE_INFO_FILE: "mapping_and_quantification-sample_info.csv"

    # (edit) output directory
    OUTPUT_DIR: "results/mapping_and_quantification"

    # (edit) read mapping
    OLEGO_SRC_DIR: "src/olego"

    OLEGO_INDEX_PATT: "data/olego/indices/mm10/index"

    OLEGO_JUNCTIONS_FILE: "data/olego/junctions/mm10.intron.hmr.bed"

    # (edit) quantification of splicing and gene expression
    QUANTAS_SRC_DIR: "src/quantas"

    QUANTAS_ANNOTATION_DIR: "data/quantas/annotations/mm10"

    # ----- GENERAL -----
    TMP_DIR: "/tmp"
    
PARAMS:
    # splicing event types to consider
    EVENT_TYPES: ["cass"]
    
    # quantification options
    ## minimum read coverage to consider splicing event
    QUANTAS_MIN_COV: 10
    ## maximum standard deviation
    QUANTAS_MAX_STD: 0.1
    
    # whether to combine groups of samples
    COMBINE_GROUPS: True
    
    # imputation options for R's impute::impute.knn()
    KNN_N_NEIGHBORS: 10
    KNN_ROWMAX: 0.5
    KNN_COLMAX: 0.8
    KNN_MAXP: 1500
    KNN_SEED: 362436069
    
    # testing
    TEST_MODE: False